providers:
  # Credit Cards
  - name: HDFC
    type: Credit Card
    domains:
      - 'Emailstatements.cards@hdfcbank.bank.in'
      - 'EmailStatements.cards@hdfcbank.net'

  - name: Axis Bank
    type: Credit Card
    domains:
      - 'cc.statements@axis.bank.in'
      - 'cc.statements@axisbank.com'

  - name: ICICI Bank
    type: Credit Card
    domains:
      - 'credit_cards@icici.bank.in'
      - 'credit_cards@icicibank.com'
      - 'estatements@icicibank.com'

  - name: IndusInd Bank
    type: Credit Card
    domains:
      - 'creditcard.estatements@indusind.com'
      - 'estatements@indusind.com'

  - name: SBI Card
    type: Credit Card
    domains:
      - 'statements@sbicard.com'
      - 'prime.card@sbicard.com'
      - 'ELITE.card@sbicard.com'
      - 'aurumcardstatement@sbicard.com'

  - name: YES Bank
    type: Credit Card
    domains:
      - 'estatement@yesbank.in'

  # Utilities
  - name: Airtel
    type: Postpaid Cell
    domains:
      - 'airtel.com'
      - 'airtel.in'
    matching_keywords:
      - 'postpaid'
      - 'mobile'
    
  - name: Airtel
    type: Wifi
    domains:
      - 'airtel.com'
      - 'airtel.in'
    matching_keywords:
      - 'broadband'
      - 'fiber'
      - 'fixed line'
      - 'wi-fi'
      - 'wifi'

  - name: Jio
    type: Prepaid Cell
    domains:
      - 'jio.com'

  - name: MPEB
    type: Electricity
    domains:
      - 'amazonpay.in'
    matching_keywords:
      - 'mpeb'
      - 'mpcz'
      - 'mpez'
      - 'madhya pradesh'

  - name: TGSPDCL
    type: Electricity
    domains:
      - 'amazonpay.in'
    matching_keywords:
      - 'tgspdcl'
      - 'telangana'
      - 'southern power distribution company of telangana'
